### ISSUE TITLE
Does this actually work?

### ISSUE THREAD

**Issue by konsumer** [valeriangalliat/fetch-cookie#1]
I am doing requests like this:

```js
var fetch = require('fetch-cookie')(require('node-fetch'))
var qs = require('qs')

var headers = {
    'Accept': 'application/json',
    'Accept-Charset': 'utf-8',
    'Keep-Alive': 'true',
    'X-Requested-By': 'hb_android_app',
    'User-Agent': 'Apache-HttpClient/UNAVAILABLE (java 1.4)'
}

// login, set coookies
function login(email, password){
    return fetch('https://www.humblebundle.com/login', {
        method: 'POST',
        credentials: 'include',
        headers: headers,
        body: qs.stringify({
            username: email,
            password: password
        })
    })
    .then(function(res){
        if (res.status !== 200){
            throw new Error('Could not login.')
        }
       // res.headers._headers['set-cookie'].join(';') is cookies.
        return res
    })
}

// get library
function library(){
    return fetch('https://www.humblebundle.com/home/library', {
        credentials: 'include',
        headers: headers
    })
    .then(function(res){
        return res.text()
    })
    .then(function(body){
        // ERR: I get login page because cookies aren't set.
        var m = /var gamekeys =  \[(".+")+\];/.exec(body)
        if (m){
            return JSON.parse('[' + m[0] + ']')
        }
    })
}

// test
login(process.env.HUMBLE_EMAIL, process.env.HUMBLE_PASSWORD)
    .then(library)

```

and no subsequent requests are using the cookies. I also tried passing an instance of  tough-cookie CookieJar as second param to `require('fetch-cookie')()`. Am I doing something wrong?

**Comment by konsumer** [comment]
I made a [quick notebook](https://tonicdev.com/konsumer/humblebundle) so you can play around with it. You will have to set `HUMBLE_EMAIL` and `HUMBLE_PASSWORD` environment variables.

**Comment by valeriangalliat** [comment]
Thanks for reporting this bug, I investigated a bit and I found the problem:

`fetch-cookie` use `res.headers.get('set-cookie')` to get the cookies, though if there are multiple `set-cookie` headers as it's the case with Humble Bundle only the first one is returned.

This bug is fixed with support for multiple `Set-Cookie` headers in e8048bfcee2b98ee7783c111d07307d03a609d06.

**Comment by konsumer** [comment]
You rock! thanks.

**Comment by konsumer** [comment]
Using it in [humblebundle](https://github.com/konsumer/humblebundle). Works great!
