### ISSUE TITLE
TypeError: res.headers.getAll is not a function

### ISSUE THREAD

**Issue by gajus** [valeriangalliat/fetch-cookie#12]
`getAll` has been removed in v2.

https://github.com/bitinn/node-fetch/blob/a345c398b30d2bccf54abc9c45071dece69a7bba/CHANGELOG.md

> Major: remove headers.getAll(); make get() return all headers delimited by commas (per spec)

**Comment by valeriangalliat** [comment]
Thanks for the heads up, supported in a BC way as of 0.6.0.
