### ISSUE TITLE
GET redirects are not being respected

### ISSUE THREAD

**Issue by gajus** [valeriangalliat/fetch-cookie#13]
I am making a GET request against https://booking.cineworld.co.uk/booking/8014/82084, which responds with 302 redirect. However, instead of following the redirect, `fetch-cookie` returns response with the 302 status.

**Comment by gajus** [comment]
I cannot understand whats the reason you have `opts.method === 'POST'` in this condition.

https://github.com/valeriangalliat/fetch-cookie/blob/aa5dc9edcbf0f05be91cbb270347d6bbbe7e66f1/node-fetch.js#L10

**Comment by valeriangalliat** [comment]
Hmm it's supposed to mirror the way [node-fetch itself works](https://github.com/valeriangalliat/node-fetch/blob/2f918a7f9c8059c994eea109f4ae4974fbdeaf41/src/index.js#L94), I'm not sure either... does the redirect handling works for you without fetch-cookie wrapper (like with native node-fetch redirect handling)?

**Comment by gajus** [comment]
> Hmm it's supposed to mirror the way node-fetch itself works, I'm not sure either... does the redirect handling works for you without fetch-cookie wrapper (like with native node-fetch redirect handling)?

Yes.

This entire implementation is either off, or I am doing something off.

Example, here you are checking whether [`opts.redirect !== 'manual'`]Phttps://github.com/valeriangalliat/fetch-cookie/blob/aa5dc9edcbf0f05be91cbb270347d6bbbe7e66f1/node-fetch.js#L13), but then you also [force it to be "manual" all the time](https://github.com/valeriangalliat/fetch-cookie/blob/aa5dc9edcbf0f05be91cbb270347d6bbbe7e66f1/node-fetch.js#L5).

Unless I am overlooking something, this shouldn't work at all.

**Comment by gajus** [comment]
This works, though.

```diff
module.exports = function nodeFetchCookieDecorator (nodeFetch, jar) {
  var fetchCookie = require('./')(nodeFetch, jar)

-  return function nodeFetchCookie (url, opts) {
-    opts = Object.assign({}, opts, { redirect: 'manual' })
+  return function nodeFetchCookie (url, userOptions) {
+    opts = Object.assign({}, userOptions, { redirect: 'manual' })

    // Forward identical options to wrapped node-fetch but tell to not handle redirection.
    return fetchCookie(url, opts)
      .then(res => {
-        var isRedirect = (res.status === 303 || ((res.status === 301 || res.status === 302) && opts.method === 'POST'))
+        var isRedirect = (res.status === 303 || ((res.status === 301 || res.status === 302) && (opts.method === 'GET' || opts.method === 'POST')))

        // Interpret the proprietary "redirect" option in the same way that node-fetch does.
-        if (isRedirect && opts.redirect !== 'manual' && opts.follow !== 0) {
+        if (isRedirect && userOptions.redirect !== 'manual' && userOptions.follow !== 0) {
          var optsForGet = Object.assign({}, {
            method: 'GET',
            body: null,
            // Since the "follow" flag is not relevant for node-fetch in this case,
            // we'll hijack it for our internal bookkeeping.
-            follow: opts.follow !== undefined ? opts.follow - 1 : undefined
+            follow: userOptions.follow !== undefined ? userOptions.follow - 1 : undefined
          })

          return nodeFetchCookie(res.headers.get('location'), optsForGet)
        } else {
          return res
        }
      })
  }
}

```

**Comment by valeriangalliat** [comment]
You're right, I didn't check that code thoroughly when merging the PR that added it.

Thanks for the patch, do you want to submit it as a PR? Otherwise I'll apply it and publish it.

**Comment by gajus** [comment]
> Thanks for the patch, do you want to submit it as a PR? Otherwise I'll apply it and publish it.

Please apply it.

**Comment by valeriangalliat** [comment]
I applied your patch, it's published as of 0.5.0. Thanks a lot!

Ideally I don't want to keep the duplicated redirect logic in this library, I'm waiting on [this pr](https://github.com/bitinn/node-fetch/pull/229) to be merged so the redirect handling would be the sole responsibility of node-fetch.

**Comment by gajus** [comment]
Thank you

**Comment by mvindahl** [comment]
I made the original PS with mistake. Thumbs up for fixing it!! :)
