### ISSUE TITLE
How to access sent cookies?

### ISSUE THREAD

**Issue by fabioemoutinho** [valeriangalliat/fetch-cookie#15]
I just couldn't find out how to retrieve sent Cookies after a fetch request. Is there a way to do it?

**Comment by FabianTe** [comment]
Are you talking about getting the cookies the server sents you once the client calls the server?

**Comment by shafferchance** [comment]
I believe that is what they mean I accomplished this by adding a custom cookie jar:
`let personalJar =  new tough.CookieJar();

const fetch = require('fetch-cookie/node-fetch')(nodeFetch, personalJar);`

Then you can access it by calling the Jar itself. Not sure if this is right, although, if there is a better I'm sure both the OP and I would love to hear it. Thanks in advance.

**Comment by FabianTe** [comment]
Thanks @shafferchance, now I understand the question.
Your answer is correct, if you want to get the cookies a server sent you, you'll have to insert your own cookie jar.

**Comment by joshmsamuels** [comment]
I just stumbled across this issue and I am curious as to why the jar cannot be exported. I also need to retrieve cookies the jar is storing but would prefer to avoid the overhead related to importing and creating an instance of the jar myself since I would only be using it to get a single cookie.

**Comment by valeriangalliat** [comment]
Done, as part of 3.1.0!

You can now access the cookie jar that way:

```js
import makeFetchCookie from 'fetch-cookie'

const fetchCookie = makeFetchCookie(fetch)

const cookie = await fetchCookie.cookieJar.getCookieString(url)

fetchCookie.cookieJar.setCookie(cookie, url)
```
