### ISSUE TITLE
Doesn't work if using headers object

### ISSUE THREAD

**Issue by mattoni** [valeriangalliat/fetch-cookie#17]
Hello,

One of my projects takes advantage of the Headers() class quite extensively. fetch-cookie tries to modify the instance, resulting in cookies not being sent. 

Adjusting line 16 to the following resolves the issue:

```
                if (opts.headers instanceof Headers) {
                    opts.headers.append("cookie", cookie);
                } else {
                    opts.headers = Object.assign(
                        opts.headers || {},
                        cookie ? { cookie: cookie } : {},
                    );
                }
```

Should I make a merge request?

**Comment by valeriangalliat** [comment]
Definitely! However the `Headers` class is not available in all environments (Node.js)... so maybe it'd be better to check `if (opts.headers && typeof opts.headers.append === 'function') {}`?

**Comment by kopax** [comment]
I am hitting the same issue, is the fix release on a repo somewhere ?

**Comment by pbadenski** [comment]
Looks like a working fix is in @kopax repo, pull request? :)
