### ISSUE TITLE
Stable ?

### ISSUE THREAD

**Issue by kopax** [valeriangalliat/fetch-cookie#18]
Hi everyone, like many people, I've ended up here.

I am not sure if I should give a try, is this completely stable ?

I have just had a try and configured my entrypoint with : 

```jsx
require('es6-promise').polyfill();
require('isomorphic-fetch');

global.fetch = require('fetch-cookie')(fetch);
global.API_URL = 'http://api-test.com:8080';
global.localStorage = window.localStorage || require('localStorage');
```

There are no cookie set in the request, it also remove and disable them.

**Comment by FabianTe** [comment]
Currently the package has some problems parsing cookies that contain commata (like in the `Expires` property). I'll try to fix some of the open issues in the next couple of weeks.

If you are having a specific problem feel free to post it here and I'll reopen the issue.
