### ISSUE TITLE
Maintainer?

### ISSUE THREAD

**Issue by OmgImAlexis** [valeriangalliat/fetch-cookie#21]
PING @valeriangalliat 

If you're looking for someone to maintain this project I'd be more than happy to step up as I've seen a few issues open from last year without any replies.

**Comment by valeriangalliat** [comment]
Thank you! Indeed I'm not really using this project since a while and I'm lacking time and motivation to maintain it, I'm glad you're offering to help! I just gave you commit access, what's your npm account so you can publish further versions?

**Comment by OmgImAlexis** [comment]
Thank you for the quick turnaround. My username is `OmgImAlexis` email is `xo@wvvw.me`.

**Comment by valeriangalliat** [comment]
Cool, you should be able to publish on npm too! Feel free to email me if anything.
