### ISSUE TITLE
Broken using node-fetch v2

### ISSUE THREAD

**Issue by diegocr** [valeriangalliat/fetch-cookie#22]
https://github.com/valeriangalliat/fetch-cookie/blob/66d8d5c307ed210340d14d068b750a9dcac841a6/index.js#L27-L29

This is not the correct way to handle cookies using node-fetch v2, since cookies could contain commas.

See https://github.com/bitinn/node-fetch/issues/251

**Comment by FabianTe** [comment]
I also would like to see this fix.

**Comment by FabianTe** [comment]
Fixed with PR https://github.com/valeriangalliat/fetch-cookie/pull/31
