### ISSUE TITLE
I hit an error: Cookie failed to parse

### ISSUE THREAD

**Issue by winglight** [valeriangalliat/fetch-cookie#23]
I checked the request on Postman that's normal with two cookies but it failed on fetch() with error:
`Error: Cookie failed to parse`
That's really confused. Any hint will be appreciated.

**Comment by ajhyndman** [comment]
I just tried installing this, and ran into the same thing.  Are there version compatibility issues we should be worried about?

**Comment by NuSkooler** [comment]
Also hitting this :(

**Comment by wcandillon** [comment]
Also getting this error 😅

**Comment by jonpacker** [comment]
Also getting this issue, also due to commas in the cookie.

**Comment by FabianTe** [comment]
I also got this error. I am fixing this in my fork and will submit a PR

**Comment by FabianTe** [comment]
The linked PR should have fixed this issue.
Please comment if this still is an issue! :)
