### ISSUE TITLE
node-fetch version 2 incompatibility

### ISSUE THREAD

**Issue by FabianTe** [valeriangalliat/fetch-cookie#24]
This package is not compatible with node-fetch version 2.

This causes a bunch of issues:

#22 - Broken using node-fetch v2
#23 - I hit an error: Cookie failed to parse
#17 - Doesn't work if using headers object

The fixes should be minor and I'll try to implement them this week in my fork.

**Comment by FabianTe** [comment]
I'll continue working on these problems in my [fork](https://github.com/Fabitee/fetch-cookie-v2). Already published it as a new [NPM package](https://www.npmjs.com/package/fetch-cookie-v2).

**Comment by valeriangalliat** [comment]
@FabianTe thanks for all that work!

I can add you as a collaborator of this repo and give you npm publish access if you want to publish a new major version of `fetch-cookie` for `node-fetch` v2, without having to use a fork and a new namespace on npm. Would you be ok with that? :)

**Comment by FabianTe** [comment]
That would be awesome. In that case I'd try to fix the relevant bugs while having `fetch-cokie` work as before.

**Comment by valeriangalliat** [comment]
This is greatly appreciated, I just sent you an invitation as collaborator on this repo and gave you npm access!

Feel free to update master and publish a new major version, don't hesitate to ask me if you have any question, my email is public on my profile, or through this issue. :)

**Comment by FabianTe** [comment]
Closing this since 2 things have been fixed and this issue hasn't any purpose anymore
