### ISSUE TITLE
Request objects handled improperly

### ISSUE THREAD

**Issue by firelizzard18** [valeriangalliat/fetch-cookie#28]
It is valid to call `fetch` with a single argument of type `Request`. This package does not handle that case.

**Comment by FabianTe** [comment]
This looks like the same issue you posted earlier. Fixing it would also resolve this. #27

**Comment by firelizzard18** [comment]
They are related but not the same. The fix I proposed for #27 would not
work for this case. I discovered this when I tried to patch fetch-cookie
locally. The `headers` property of a Request object cannot be written, and
writing properties to a Headers object either fails or has no effect. To
set cookies on a Request, you must use `request.headers.set('Cookies',
value)`.
