### ISSUE TITLE
Travis CI

### ISSUE THREAD

**Issue by FabianTe** [valeriangalliat/fetch-cookie#29]
@valeriangalliat 

I'd like to include the Travis CI I used in my fork to ensure better stability.
If you are okay with it I'd need you to enable it, my access rights are not enough to do that.
In my fork you can find the Travis YAML configuration file.

**Comment by valeriangalliat** [comment]
I activated the Travis CI integration https://travis-ci.org/valeriangalliat/fetch-cookie, I believe if you add back https://github.com/valeriangalliat/fetch-cookie/pull/26 into master it should catch up automatically?

**Comment by FabianTe** [comment]
I added it as a new branch and will merge it, this should do fine. Thank you!
