### ISSUE TITLE
Tough-cookie <2.3.0 has known vulnerabilities

### ISSUE THREAD

**Issue by kentandersen** [valeriangalliat/fetch-cookie#3]
> [Tough-cookie] versions 0.9.7 through 2.2.2 contain a vulnerable regular expression that, under certain conditions involving long strings of semicolons in the "Set-Cookie" header, causes the event loop to block for excessive amounts of time.
https://nodesecurity.io/advisories/130

Please upgrade to version 2.3.0 or above 😃

**Comment by valeriangalliat** [comment]
Thanks!
