### ISSUE TITLE
Unable to set default/existing cookies...

### ISSUE THREAD

**Issue by aeroxy** [valeriangalliat/fetch-cookie#34]
There isn't any method provided to set/add cookies manually.

**Comment by FabianTe** [comment]
Have you tried [using a custom cookie jar](https://github.com/valeriangalliat/fetch-cookie#custom-cookie-jar)? That way you can insert your own cookie into the jar and then it will be sent with every request.

**Comment by kevin4dhd** [comment]
how to use

**Comment by valeriangalliat** [comment]
Yo! I updated the readme a bit with v2, and the custom cookie jar that Fabian pointed out above is still relevant for setting custom cookies, so I'll close this for now. Please re-open the issue if it's still not clear :)
