### ISSUE TITLE
Denodify fails

### ISSUE THREAD

**Issue by nonyy** [valeriangalliat/fetch-cookie#35]
Here's a code sample:
https://repl.it/repls/CheapButteryBudgetrange

Let me know if it works. Click run to run.
Any idea how to fix it?

**Comment by nonyy** [comment]
![problem jpg](https://user-images.githubusercontent.com/18537226/52236060-186dde80-28c6-11e9-85f6-6663c22f1032.png)

**Comment by FabianTe** [comment]
This is not the fault auf denodify. This will also happen when you use the default callback version: https://repl.it/repls/WillingBadSuperuser

The actual error is your usage of `cookiejar.setCookie`. Look at the [`tough-cookie` implementation](https://github.com/salesforce/tough-cookie/blob/43507052a70751501d52aad38bd837bb2edfedd8/lib/cookie.js#L995-L1007):

```js
CookieJar.prototype.setCookie = function(cookie, url, options, cb) {
  var err;
  var context = getCookieContext(url);
  if (options instanceof Function) {
    cb = options;
    options = {};
  }

  var host = canonicalDomain(context.hostname);
  var loose = this.enableLooseMode;
  if (options.loose != null) {
    loose = options.loose;
  }

  // ...
}
```

The error `Cannot read property 'loose' of undefined` is a result of you not correctly supplying the parameters.

Try supplying the correct parameters (at least `cookie` and `url`).

**Comment by nonyy** [comment]
You are right, it can be closed. I forgot to mention I had found the cause... long ago.
