### ISSUE TITLE
Error: Cookie not in this host's domain.

### ISSUE THREAD

**Issue by pongstylin** [valeriangalliat/fetch-cookie#38]
The decorator throws an exception on this line if the server returned cookies that are outside of its domain.  While such cookies certainly do not belong in the jar, I would still like to get the fetched response.

await Promise.all(cookies.map((cookie) => setCookie(cookie, res.url)))

**Comment by FabianTe** [comment]
This is enfored by `tough-cookie`: [Relevant code where the error originates from.](https://github.com/salesforce/tough-cookie/blob/master/lib/cookie.js#L1040-L1049)

As described in [this similar issue](https://github.com/request/request/issues/794#issuecomment-34084788) RFC states that such cookies are invalid and will be rejected by most browsers anyway.

Personally I agree that there may be cases where you still want the response, but this is out of the scope of this module. You will have to look into `tough-cookie`, alternatives to it, or a custom implementation if you really want to store these cookies.

**Comment by pongstylin** [comment]
"if you really want to store these cookies."
To be clear, I don't want to store these cookies.  As you say, browsers reject them, so I want to reject them too.  Browsers still give you a response, however, and I want the response here as well.  Tough cookie is doing the right thing by raising an exception since such cookies do not belong in the jar.  But this module should not penalize me for something outside of my control.  IMHO, the right thing to do is to silently reject such cookies and still give me a response just like a browser.  You may offer an option to be more strict than a browser and loudly reject the cookies.

**Comment by FabianTe** [comment]
Agree. But still, I think it's your responsibility to use a cookie-store that behaves the way you want.

I'd use a tough-cookie instance and overwrite the `setCookie` function to work the way I expect it to.
