### ISSUE TITLE
Doesn't work when set-cookie is in 302 redirects and redirect is set to 'follow'

### ISSUE THREAD

**Issue by vmirage** [valeriangalliat/fetch-cookie#39]
When redirect is set to 'follow' which is the default, the set-cookie inside the 302 redirect page won't be set in the cookie jar.

**Comment by ciricc** [comment]
Same problem

**Comment by ciarans** [comment]
Yep same problem :(

**Comment by valeriangalliat** [comment]
Hey there! This should now work out of the box with v2.0.0 that I just published :)
