### ISSUE TITLE
Library ignores proxy agent option on redirects

### ISSUE THREAD

**Issue by ciricc** [valeriangalliat/fetch-cookie#47]
In your code follow redirects works fine, but when you imitate following you are forgetting about proxy agent option and custom headers like User-Agent and other.

**Comment by rpulivarthy** [comment]
There is a [PR](https://github.com/valeriangalliat/fetch-cookie/pull/45) that should address this issue.

**Comment by valeriangalliat** [comment]
I believe this is no longer necessary since https://github.com/valeriangalliat/fetch-cookie/commit/8efac8ff47c2ef9627f2e7642208bc0a9537367e (released in 0.10.0), please reopen if still you run into this issue! :heart:
