### ISSUE TITLE
Not passing options further in redirects

### ISSUE THREAD

**Issue by jajcek** [valeriangalliat/fetch-cookie#48]
Hi,

in the node-fetch decorator `fetch-cookie/node-fetch` the options provided by user are not passed further through redirects, is it intentional? In some authentications (e.g. google) they require to have user-agent in every redirect, otherwise it forwards to inappropriate url. I think this line:

```
const optsForGet = Object.assign({}, {
```
should be changed into:
```
const optsForGet = Object.assign({}, userOptions, {
```
Br,
hh

**Comment by valeriangalliat** [comment]
This is fixed thanks to #55, published as 0.10.0!
