### ISSUE TITLE
It could work on browser?

### ISSUE THREAD

**Issue by caub** [valeriangalliat/fetch-cookie#5]
I see `window.fetch` in source, but tough-cookie is node-only, how would this be used for a client platform (supporting or not cookies)?

**Comment by valeriangalliat** [comment]
Hmm not sure why I used `window.fetch`, it doesn't really makes sense since browsers have native `fetch` with cookie support already. I didn't know tough-cookie was Node only but it's just another reason for not using this library in the browser I guess.
