### ISSUE TITLE
Typescript type definitions are incorrect

### ISSUE THREAD

**Issue by cheeseandcereal** [valeriangalliat/fetch-cookie#50]
The current types in `index.d.ts` do not allow importing the node-fetch submodule (`fetch-cookie/node-fetch`)

Additionally, while the module supports custom cookie jar implementations, the types now restrict it to be ONLY the tough-cookie cookie jar implementation, which breaks typescript usage which was previously using a custom cookie jar since the v0.9.0 release.

**Comment by valeriangalliat** [comment]
Ah that makes sense, thanks for reporting, Adam.

I merged the PR that adds types yesterday without considering the fact that I don't have much time to allocate to open source these days to handle its eventual issues, do you wanna give a hand?

**Comment by cheeseandcereal** [comment]
Sure, added a PR which should fix these issues
