### ISSUE TITLE
node-fetch.js should treat status 308 as a redirect

### ISSUE THREAD

**Issue by denishowew** [valeriangalliat/fetch-cookie#57]
[PR 55](https://github.com/valeriangalliat/fetch-cookie/pull/55) added support for [HTTP status 307](https://httpstatuses.com/307) (temporary redirect with no change of method).
Should _all_ 3XX codes be treated as redirects?  Certainly my current favourite,
[308](https://httpstatuses.com/308) (permanent redirect), should.

Also not recognised:
* 300 Multiple Choices
* 304 Not Modified
* 305 Use Proxy

**Comment by valeriangalliat** [comment]
Hey! I just published fetch-cookie@2.0.0 with an improved redirect logic and now handles all of those redirect statuses. It should basically behave the same as node-fetch as far as redirects are concerned now. Cheers :)
