### ISSUE TITLE
Set-Cookie typings are incorrect

### ISSUE THREAD

**Issue by heyitsaamir** [valeriangalliat/fetch-cookie#59]
```
setCookie(cookieString: string, currentUrl: string, cb: (err: any) => void, opts: { ignoreError: boolean }): void;
```

Please correct me if I'm wrong --
The current set-cookie typings don't have the callback as the final arg, and the package promisifies that function (which needs that callback to the the final argument). Should opts and cb be swapped?

**Comment by valeriangalliat** [comment]
Fixed with https://github.com/valeriangalliat/fetch-cookie/pull/60 thanks for the PR =)
