### ISSUE TITLE
Unable to use import syntax 

### ISSUE THREAD

**Issue by joshmsamuels** [valeriangalliat/fetch-cookie#61]
Hi,

I am unfamiliar with how to use the new `import` syntax with this package so I was thinking it might not play nicely with the way the export was defined. 

I would be happy to create a PR if this is an issue and we can decide on the correct approach since I cannot think of one that would not be a breaking change to the existing API.

**Comment by valeriangalliat** [comment]
Hey! You should be able to use `import { default as fetchCookie } from 'fetch-cookie'`

Let me know if that works for you :)

**Comment by joshmsamuels** [comment]
yup that did solve the issue thanks a lot!

For anyone else that sees this -- to get the fetch function you need to call fetchCookie with your fetch function after the import statement
```
import { default as fetchCookie } from 'fetch-cookie'
const fetchWithCookies = fetchCookie(fetchFunc)
```

(sorry for not closing this sooner)

**Comment by joshmsamuels** [comment]
yup that did solve the issue thanks a lot!

For anyone else that sees this -- to get the fetch function you need to call fetchCookie with your fetch function after the import statement

import { default as fetchCookie } from 'fetch-cookie'
const fetchWithCookies = fetchCookie(fetchFunc)
(sorry for not closing this sooner)
