### ISSUE TITLE
Example in documentation doesn't works with fetch-cookie v2 e

### ISSUE THREAD

**Issue by xfournet** [valeriangalliat/fetch-cookie#68]
The typescript definition doesn't works.
See https://codesandbox.io/s/jolly-cookies-8nfzz3?file=/index.ts

* First issue
![image](https://user-images.githubusercontent.com/461943/156670183-cee481c3-d262-4e6a-8619-3b8c0afba046.png)

* After adding compilerOptions.esModuleInterop to true, 2nd issue because jar parameter is not declared as optional (while there is a provided default value see https://github.com/valeriangalliat/fetch-cookie/blob/fd2e1969efb84cae389f93fcc7cf0a7dd947b27b/src/index.ts#L210
![image](https://user-images.githubusercontent.com/461943/156670839-f0603ac9-fdff-4703-891a-24ac18f01675.png)

* After adding manually tough.cookieJar, 3rd issue regarding missing properties size and buffer in Request type
![image](https://user-images.githubusercontent.com/461943/156671186-c6157fb3-f927-4a59-9b43-36be111a24a9.png)

**Comment by valeriangalliat** [comment]
Hey! Thanks for reporting, I just fixed the types in 2.0.1 and it should now work like in the readme! Let me know if that works for you :)

**Comment by xfournet** [comment]
Hi! Thanks you very much for fixing this issue quickly. It works perfectly now :)
