### ISSUE TITLE
How to include cookie on cookie jar?

### ISSUE THREAD

**Issue by swassapparel1** [valeriangalliat/fetch-cookie#74]
Hi, how can I add a specific cookie to the cookie jar?

I'm currently using the wrapper. 

const nodeFetch = require('node-fetch');
const fetch = require('fetch-cookie/node-fetch')(nodeFetch); //NODE FETCH 2.6.7 //FETCH-COOKIE 1.00

I'm using puppeteer to login on a website that has a captcha and on successful log in I'm getting that puppeteer browser cookies and wanted to pass it on the cookie jar.

Thank you!

**Comment by valeriangalliat** [comment]
Hey! For this you need to use a [custom cookie jar](https://github.com/valeriangalliat/fetch-cookie#custom-cookie-jar)

Then you can use the [tough-cookie API](https://www.npmjs.com/package/tough-cookie) to set your specific cookie

Lmk if that helps :)

**Comment by swassapparel1** [comment]
Thank you for your reply! I really appreciate your help! 

Just wanted to ask for example if I’ll be using a custom cookie jar using this code. How can I set the cookies via tough-cookie API? Can you give an example code snippet? Thank you!

const nodeFetch = require('node-fetch')
const fetchCookie = require('fetch-cookie')
const fetch = fetchCookie(nodeFetch, new fetchCookie.toughCookie.CookieJar())

**Comment by valeriangalliat** [comment]
Something like this should do:

```js
const nodeFetch = require('node-fetch')
const fetchCookie = require('fetch-cookie')

const cookieJar = new fetchCookie.toughCookie.CookieJar()
cookieJar.setCookie('foo=bar', 'https://url.associated.with.the.cookie/')

const fetch = fetchCookie(nodeFetch, cookieJar)
```

**Comment by donething** [comment]
Can `cookieString` be multiple key-values? such as 'name=Li; age=23', then I only get 'name=Li‘.
