### ISSUE TITLE
the redirect implementation does not update the host header

### ISSUE THREAD

**Issue by joerg1985** [valeriangalliat/fetch-cookie#77]
The redirect implementation does not update the host header if the redirect is to another domain.
This will lead to strange SSL exceptions, when the host header does not match in firefox.

**Comment by valeriangalliat** [comment]
Hey, sorry for the late reply

Were you explicitly passing the `host` header in the fetch options, e.g.:

```
fetch('http://test.com', { headers: { host: 'test.com' } })
```

In this case yeah fetch-cookie doesn't currently handle this, but should be easy to patch

**Comment by valeriangalliat** [comment]
Fixed the above case with explicit host passing as part of 3.1.0 :)
