### ISSUE TITLE
headers array unsupported

### ISSUE THREAD

**Issue by sparecycles** [valeriangalliat/fetch-cookie#80]
## Observation 

https://fetch.spec.whatwg.org/#typedefdef-headersinit lists two options for the headers field (passing the `Headers` object isn't actually in the spec).

In `lib.dom.d.ts` the field has the following type ( [link](https://github.com/microsoft/TypeScript/blob/a3c5d5d37e54610d2e86ec44b1692522a3ed6931/src/lib/dom.generated.d.ts#L27983) )

```ts
type HeadersInit = [string, string][] | Record<string, string> | Headers;
```

![image](https://github.com/valeriangalliat/fetch-cookie/assets/719818/ea459817-1c30-4303-bf7a-3aba8710ccf3)

This array format is unsupported by the current code (only `Headers` objects or the dictionary form are).

## Impact

```js
// this works as expected the first time only, when there's no cookies yet
await fetchCookie(url, { headers: [["x-my-header": "my-header-value"]] });

// this overwrites the headers with the cookie -- removing any headers passed here. ⚠️ 
await fetchCookie(url, { headers: [["x-my-header": "my-header-value"]] });
```

**Comment by valeriangalliat** [comment]
Oh good catch, fixed as part of 3.1.0!
