### ISSUE TITLE
Request: allow get cookjar after fetch

### ISSUE THREAD

**Issue by bluelovers** [valeriangalliat/fetch-cookie#82]
```ts
fetchCookie('a url')
	.then(res => {
		console.dir(res)
		console.dir(res.cookieJar) // <== something like this
	})
;
```

**Comment by cvbge** [comment]
Me too. Same as https://github.com/valeriangalliat/fetch-cookie/issues/15#issuecomment-751534103
I want to access internal cookie Jar, I don't want to use custom cookie jar. (I don't need to have more than one cookie jars, I'm ok with the internal jar, using custom jar only to access the cookies looks like not needed work)

**Comment by valeriangalliat** [comment]
Done, as part of 3.1.0!

You can now access the cookie jar that way:

```js
import makeFetchCookie from 'fetch-cookie'

const fetchCookie = makeFetchCookie(fetch)

const cookie = await fetchCookie.cookieJar.getCookieString(url)

fetchCookie.cookieJar.setCookie(cookie, url)
```
