### ISSUE TITLE
How do I pass options to undici fetch (not fetchCookie) ??

### ISSUE THREAD

**Issue by OZZlE** [valeriangalliat/fetch-cookie#85]
import { fetch as uFetch } from "undici";
    import fetchCookie from "fetch-cookie";

    export const fetchPreserveCookies = async (args: any) => { // @todo fix any
        const orgRejectUnauthorized = process.env["NODE_TLS_REJECT_UNAUTHORIZED"];
        process.env["NODE_TLS_REJECT_UNAUTHORIZED"] = "0";
    
        const resp = fetchCookie(uFetch.apply([...args]));
    
        process.env["NODE_TLS_REJECT_UNAUTHORIZED"] = orgRejectUnauthorized;
    
        return resp;
    };

    /*
     ⨯ unhandledRejection: TypeError: Failed to parse URL from undefined
    at Array.fetch (webpack-internal:///(rsc)/./node_modules/undici/index.js:112:13) {
    [cause]: TypeError [ERR_INVALID_URL]: Invalid URL
      at new NodeError (node:internal/errors:405:5)
    */

**Comment by valeriangalliat** [comment]
Hey! The `apply` function takes the `this` value as first argument, and an array as second argument

You should do `const resp = fetchCookie(uFetch.apply(this, args));`
