### ISSUE TITLE
touch-cookie v5 upgrade

### ISSUE THREAD

**Issue by danielweck** [valeriangalliat/fetch-cookie#87]
FYI:

https://github.com/valeriangalliat/fetch-cookie/blob/628d0587a71450bcf713b3852ff2550d26d436bf/package.json#L38

https://github.com/valeriangalliat/fetch-cookie/blob/628d0587a71450bcf713b3852ff2550d26d436bf/package.json#L48

Changelog (note the native TypeScript support, which negates the need for `@types/tough-cookie`):

https://github.com/salesforce/tough-cookie/releases/tag/v5.0.0

**Comment by valeriangalliat** [comment]
Released with 3.1.0!
